### PR TITLE
Update man pages translation by Olesya Gerasimenko

### PR DESCRIPTION
**Pull request by darktemplarbasealt**
Signed-off-by: Olesya Gerasimenko <gammaray@basealt.ru>
Signed-off-by: Aleksei Nikiforov <darktemplar@basealt.ru>

### CODE REVIEW

**Comment by darktemplarbasealt** [comment]
Can someone review and merge this request please?

**Comment by doverride** [comment]
I verified this with Google Translate: Looks good.

**Comment by darktemplarbasealt** [comment]
> I verified this with Google Translate: Looks good.

Could this change be merged in that case?

**Comment by darktemplarbasealt** [comment]
Thank you

**Pull request merged**
