### PR TITLE
Add russian translations for man pages

### PR DESCRIPTION
**Pull request by darktemplarbasealt**

### CODE REVIEW

**Comment by darktemplarbasealt** [comment]
Can someone take a look at this pull request please?

**Comment by stephensmalley** [comment]
@bachradsusi @rhatdan Probably needs review by whomever at Red Hat handles translations?

**Comment by bachradsusi** [comment]
In Fedora we have https://src.fedoraproject.org/repo/pkgs/rpms/policycoreutils/policycoreutils_man_ru2.tar.bz2/sha512/7272801da169b8d7dd3f8b7e368a63a4fbb7ae94599f9384bc450d142e6b2a3805ab542d650cbe9c8978c2d8e5c56ef4c11f361abfefeaf184ec3a4b0d2afb4c/policycoreutils_man_ru2.tar.bz2 which wasn't updated since 2010 and it looks like nobody has complained about outdated translations so far. So I doubt it's worth to maintain this in upstream sources.

Anyway, both patches miss Signed-off-by: lines which could be important as the translations come from a different author.

**Comment by darktemplarbasealt** [comment]
This pull request contains more translated pages than mentioned archive from Fedora. Why is it not worth it to maintain translations in the upstream sources? Everyone who uses selinux and needs translated documentation will be able to get it this way, and if translation gets outdated eventually - to update it.

As for "Signed-off-by" lines, is it enough if I sign it? I received translated pages in form of tarball and made a commit using contents of that tarball. If it's still necessary to get sign off from translator too, I'll work on it.

**Comment by darktemplarbasealt** [comment]
I've got sign-offs. Please let me know if anything else is needed.

**Comment by stephensmalley** [comment]
My $0.02: I don't have a problem with including such translations upstream but we need an independent party from the submitter/author who can review their content, and unfortunately I am not able to do so.

**Comment by doverride** [comment]
stephensmalley <notifications@github.com> writes:

> My $0.02: I don't have a problem with including such translations upstream but we need an independent party from the submitter/author who can
> review their content, and unfortunately I am not able to do so.

Is Google translate good enough? The parts I looked using it at looked
fine (I admit I only did a few tests so far)

>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by doverride** [comment]
I will *try* to work my way through them using google translate, hopefully a couple a day and use this comment to keep a tab. It will take time. The shear amount of man pages painfully reminds me of how much dead-weight the project carries...

Reviewed:
✔️  checkpolicy/ru/checkmodule.8
✔️  checkpolicy/ru/checkpolicy.8
✔️  gui/ru/selinux-polgengui.8

Todo:

🔜  gui/ru/system-config-selinux.8
🔜  libselinux/man/ru/man5/booleans.5
🔜  libselinux/man/ru/man5/customizable_types.5
🔜  libselinux/man/ru/man5/default_contexts.5
🔜  libselinux/man/ru/man5/default_type.5
🔜  libselinux/man/ru/man5/failsafe_context.5
🔜  libselinux/man/ru/man5/local.users.5
🔜  libselinux/man/ru/man5/removable_context.5
🔜  libselinux/man/ru/man5/secolor.conf.5
🔜  libselinux/man/ru/man5/securetty_types.5
🔜  libselinux/man/ru/man5/selabel_db.5
🔜  libselinux/man/ru/man5/selabel_file.5
🔜  libselinux/man/ru/man5/selabel_media.5
🔜  libselinux/man/ru/man5/selabel_x.5
🔜  libselinux/man/ru/man5/service_seusers.5
🔜  libselinux/man/ru/man5/seusers.5
🔜  libselinux/man/ru/man5/user_contexts.5
🔜  libselinux/man/ru/man5/virtual_domain_context.5
🔜  libselinux/man/ru/man5/virtual_image_context.5
🔜  libselinux/man/ru/man8/avcstat.8
🔜  libselinux/man/ru/man8/booleans.8
🔜  libselinux/man/ru/man8/getenforce.8
🔜  libselinux/man/ru/man8/getsebool.8
🔜  libselinux/man/ru/man8/matchpathcon.8
🔜  libselinux/man/ru/man8/sefcontext_compile.8
🔜  libselinux/man/ru/man8/selinux.8
🔜  libselinux/man/ru/man8/selinuxenabled.8
🔜  libselinux/man/ru/man8/selinuxexeccon.8
🔜  libselinux/man/ru/man8/setenforce.8
🔜  libselinux/man/ru/man8/togglesebool.8
🔜  libsemanage/man/ru/man5/semanage.conf.5
🔜  libsepol/man/ru/man8/chkcon.8
🔜  mcstrans/man/ru/man8/mcs.8
🔜  mcstrans/man/ru/man8/mcstransd.8
🔜  mcstrans/man/ru/man8/setrans.conf.8
🔜  policycoreutils/load_policy/ru/load_policy.8
🔜  policycoreutils/man/ru/man5/selinux_config.5
🔜  policycoreutils/newrole/ru/newrole.1
🔜  policycoreutils/run_init/ru/open_init_pty.8
🔜  policycoreutils/run_init/ru/run_init.8
🔜  policycoreutils/scripts/ru/fixfiles.8
🔜  policycoreutils/secon/ru/secon.1
🔜  policycoreutils/semodule/ru/genhomedircon.8
🔜  policycoreutils/semodule/ru/semodule.8
🔜  policycoreutils/sestatus/ru/sestatus.8
🔜  policycoreutils/sestatus/ru/sestatus.conf.5
🔜  policycoreutils/setfiles/ru/restorecon.8
🔜  policycoreutils/setfiles/ru/restorecon_xattr.8
🔜  policycoreutils/setfiles/ru/setfiles.8
🔜  policycoreutils/setsebool/ru/setsebool.8
🔜  python/audit2allow/ru/audit2allow.1
🔜  python/chcat/ru/chcat.8
🔜  python/semanage/ru/semanage-boolean.8
🔜  python/semanage/ru/semanage-dontaudit.8
🔜  python/semanage/ru/semanage-export.8
🔜  python/semanage/ru/semanage-fcontext.8
🔜  python/semanage/ru/semanage-ibendport.8
🔜  python/semanage/ru/semanage-ibpkey.8
🔜  python/semanage/ru/semanage-import.8
🔜  python/semanage/ru/semanage-interface.8
🔜  python/semanage/ru/semanage-login.8
🔜  python/semanage/ru/semanage-module.8
🔜  python/semanage/ru/semanage-node.8
🔜  python/semanage/ru/semanage-permissive.8
🔜  python/semanage/ru/semanage-port.8
🔜  python/semanage/ru/semanage-user.8
🔜  python/semanage/ru/semanage.8
🔜  python/sepolicy/ru/sepolicy-booleans.8
🔜  python/sepolicy/ru/sepolicy-communicate.8
🔜  python/sepolicy/ru/sepolicy-generate.8
🔜  python/sepolicy/ru/sepolicy-gui.8
🔜  python/sepolicy/ru/sepolicy-interface.8
🔜  python/sepolicy/ru/sepolicy-manpage.8
🔜  python/sepolicy/ru/sepolicy-network.8
🔜  python/sepolicy/ru/sepolicy-transition.8
🔜  python/sepolicy/ru/sepolicy.8
🔜  restorecond/ru/restorecond.8
🔜  sandbox/ru/sandbox.5
🔜  sandbox/ru/sandbox.8
🔜  sandbox/ru/seunshare.8
🔜  semodule-utils/semodule_expand/ru/semodule_expand.8
🔜  semodule-utils/semodule_link/ru/semodule_link.8
🔜  semodule-utils/semodule_package/ru/semodule_package.8
🔜  semodule-utils/semodule_package/ru/semodule_unpackage.8

**Comment by doverride** [comment]
All is reviewed. All is good.
Signed-off-by: Dominick Grift <dac.override@gmail.com>

**Comment by bachradsusi** [comment]
@doverride Thanks for the review!

I've resend this PR to the selinux@vger.kernel.org mailing list in order to follow the procedure. If there's no other objection it will be merged in 2 days.

**Pull request merged**
