### PR TITLE
Consider a version format of X.Y for selinux

### PR DESCRIPTION
**Pull request by HuKeping**
As per discussed at #270 and [mailing list](https://lore.kernel.org/selinux/87d004wan2.fsf@redhat.com/T/#u), we consider a version format of X.Y starting at 3.2.

This patch set contains 3 commits:

- [Patch 1/3] Introduce VERSION file for selinux
- [Patch 2/3] Use X.Y instead of date for release tag
- [Patch 3/3] Simplify the tarball generating scripts

### CODE REVIEW

**Comment by HuKeping** [comment]
Have tested on my host, here's the output:
```
$ scripts/release 
Add the following to the ../selinux.wiki/Releases.md wiki page:

## Release 3.10

[Release Notes](https://github.com/SELinuxProject/selinux/releases/download/3.10/RELEASE-3.10.txt)

[full log](https://github.com/SELinuxProject/selinux/releases/download/3.10/log-3.10.txt)

[short log](https://github.com/SELinuxProject/selinux/releases/download/3.10/shortlog-3.10.txt)

[checkpolicy-3.1.tar.gz](https://github.com/SELinuxProject/selinux/releases/download/3.10/checkpolicy-3.1.tar.gz) dfc7707070520c93b14fbbdfdbe081364d806bf28e3e79e10318c2594c77bbb2

[libselinux-3.1.tar.gz](https://github.com/SELinuxProject/selinux/releases/download/3.10/libselinux-3.1.tar.gz) ea5dcbb4d859e3f999c26a13c630da2f16dff9462e3cc8cb7b458ac157d112e7

[libsemanage-3.1.tar.gz](https://github.com/SELinuxProject/selinux/releases/download/3.10/libsemanage-3.1.tar.gz) 22d6c75526e40d1781c30bcf29abf97171bdfe6780923f11c8e1c76a75a21ff8

[libsepol-3.1.tar.gz](https://github.com/SELinuxProject/selinux/releases/download/3.10/libsepol-3.1.tar.gz) ae6778d01443fdd38cd30eeee846494e19f4d407b09872580372f4aa4bf8a3cc

[mcstrans-3.1.tar.gz](https://github.com/SELinuxProject/selinux/releases/download/3.10/mcstrans-3.1.tar.gz) cc918576c17340fc944849d785e2a7400b269ef079a36b871c140504164d6a45

[policycoreutils-3.1.tar.gz](https://github.com/SELinuxProject/selinux/releases/download/3.10/policycoreutils-3.1.tar.gz) c889f62ee80f8b6a369469a9b8af51f5b797975aeaa291f5c5960cc12eed1934

[restorecond-3.1.tar.gz](https://github.com/SELinuxProject/selinux/releases/download/3.10/restorecond-3.1.tar.gz) 82ca45099685a45d718f11f8859963c1ba83d98e510312cbf0b7dc5664c60ad0

[secilc-3.1.tar.gz](https://github.com/SELinuxProject/selinux/releases/download/3.10/secilc-3.1.tar.gz) 86117246fec3017af710a9ff7c1dae3ed1cd571e232a86cff3e2a3de2d6aa65c

[selinux-dbus-3.1.tar.gz](https://github.com/SELinuxProject/selinux/releases/download/3.10/selinux-dbus-3.1.tar.gz) 61f936d200ff8302c513883c67bb7c4c496513e78122954cbd33db62086a06f2

[selinux-gui-3.1.tar.gz](https://github.com/SELinuxProject/selinux/releases/download/3.10/selinux-gui-3.1.tar.gz) 40775eaef965259ca2f8ad49c23b03ff2c8f70808a9e0587b1075970b2509c3d

[selinux-python-3.1.tar.gz](https://github.com/SELinuxProject/selinux/releases/download/3.10/selinux-python-3.1.tar.gz) f4d0a1a030bc291a6af498b26e0676b745075dd289a8ba16cdec86c3ea8f2f02

[selinux-sandbox-3.1.tar.gz](https://github.com/SELinuxProject/selinux/releases/download/3.10/selinux-sandbox-3.1.tar.gz) c79b958e2f64570a59e60638fd13c15fd77c7c2bbac31c7ad4afb03718432b84

[semodule-utils-3.1.tar.gz](https://github.com/SELinuxProject/selinux/releases/download/3.10/semodule-utils-3.1.tar.gz) 0cc37f9cec751d9c2abb5f2b228b060567e973cb47c19b53b8a4a7378baaa853

And then run:
  cd ../selinux.wiki
  git commit  -m "Release 3.10" -a -s
  git push

Push the release and its tags to git via:
  git push
  git push --tags

Create a new release from the latest tag on https://github.com/SELinuxProject/selinux/tags

Add files from releases/3.10 as assets to the new github release
hukeping@workwork:~/opensource/selinux$ echo $?
0
hukeping@workwork:~/opensource/selinux$ git status .
On branch master
Your branch is ahead of 'origin/master' by 4 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean


$ ls releases/
3.10


$ ls releases/3.10/
checkpolicy-3.1.tar.gz  libsepol-3.1.tar.gz         restorecond-3.1.tar.gz   selinux-gui-3.1.tar.gz      semodule-utils-3.1.tar.gz
libselinux-3.1.tar.gz   mcstrans-3.1.tar.gz         secilc-3.1.tar.gz        selinux-python-3.1.tar.gz
libsemanage-3.1.tar.gz  policycoreutils-3.1.tar.gz  selinux-dbus-3.1.tar.gz  selinux-sandbox-3.1.tar.gz
```

**Comment by HuKeping** [comment]
Ping @bachradsusi  PTAL

**Comment by bachradsusi** [comment]
Sorry, I've been busy. I've resent it to the mailing list. Looks good to me so I'll provide ack and if there's no other objection it would be merged during next 3 working days.

Thanks!

**Comment by HuKeping** [comment]
Commit https://github.com/SELinuxProject/selinux/commit/f5f63035fab4879d1872764294df801a7896e238 upstream. 

Closing.

**Pull request closed without merging**
