### PR TITLE
Fix building against musl and uClibc libc libraries.

### PR DESCRIPTION
**Pull request by aduskett**
Currently, the src/Makefile provides the FTS_LDLIBS when building against musl
or uClibc. However, this is missing from utils/Makefile, which causes linking
to fail.

Add the FTS_LDLIBS variable to the LDLIBS variable in utils/Makefile to fix
compiling against uClibc and musl.

### CODE REVIEW

**Comment by bachradsusi** [comment]
Hello, thank you for your bug report. In order for your patch to be merged, it needs to follow some rules that are written file CONTRIBUTING.md (https://github.com/SELinuxProject/selinux/blob/master/CONTRIBUTING.md). More precisely:

  * Please send your patches to the mailing list selinux@vger.kernel.org (for example by using git format-patch and git send-email) in order for the developers to review and test it. If you have trouble doing this, I can forward your patch for you.
  *  Please add a "Signed-off-by:" line to the commit message. This means your code meets the Developer's certificate of origin which is written in CONTRIBUTING.md.

**Comment by williamcroberts** [comment]
@aduskett can you add a signed off line, we need that at a minimum? (git commit --amend -s && git push -f aduskett  fix-musl-and-uclibc-builds:fix-musl-and-uclibc-builds) Also, could you mail the patch to the mailing list?

**Comment by aduskett** [comment]
> @aduskett can you add a signed off line, we need that at a minimum? (git commit --amend -s && git push -f aduskett fix-musl-and-uclibc-builds:fix-musl-and-uclibc-builds) Also, could you mail the patch to the mailing list?

Yes of course!

**Comment by williamcroberts** [comment]
> > @aduskett can you add a signed off line, we need that at a minimum? (git commit --amend -s && git push -f aduskett fix-musl-and-uclibc-builds:fix-musl-and-uclibc-builds) Also, could you mail the patch to the mailing list?
> 
> Yes of course!

Bump? Can you at least add the signed-off by?

**Comment by aduskett** [comment]
Ugh, sorry! These last few weeks have been crazy with the whole COVID thing, I will create a proper patch and push to the mailing list right now :)

**Comment by aduskett** [comment]
So I * think * I sent the patch to the correct mailing list.

**Comment by WOnder93** [comment]
@aduskett It still doesn't show up on https://lore.kernel.org/selinux/, nor in my mailbox (not counting the one you sent to selinux@lists.fedoraproject.org).

**Comment by aduskett** [comment]
Ah! There we go! It now properly shows up on https://lore.kernel.org/selinux/

**Pull request closed without merging**
