### PR TITLE
python/restorecon: add force option

### PR DESCRIPTION
**Pull request by vashirov**
This adds 'force' keyword argument to selinux.restorecon() function
using SELINUX_RESTORECON_SET_SPECFILE_CTX flag similar to -F option in restorecon util.

### CODE REVIEW

**Comment by bachradsusi** [comment]
Please submit all bug reports and patches to selinux@vger.kernel.org.
Subscribe by sending "subscribe selinux" in the body of an email
to majordomo@vger.kernel.org - https://github.com/SELinuxProject/selinux/blob/master/README

**Comment by bachradsusi** [comment]
Also please add Signed-off-by: line, git commit [-s, --signoff] ...

**Comment by stephensmalley** [comment]
Are you having problems with subscribing to or posting to the selinux list?  If so, let us know. Otherwise, please submit your patch there with a Signed-off-by line and we'll review it.

**Comment by vashirov** [comment]
Sorry, I missed notifications. 
I've sent email to the mailing list. I guess this PR can be closed.
Thanks!

**Comment by fishilico** [comment]
Merged as https://github.com/SELinuxProject/selinux/commit/474a09233c27f8db0330a271f921f874f5f91c54

**Pull request closed without merging**
